### ISSUE TITLE
npm install failing with react-native RC releases

### ISSUE THREAD

**Issue by chandu0101** [thewei/react-native-store#15]
`npm ERR! peerinvalid The package react-native@0.16.0-rc does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-store@0.2.0 wants react-native@>=0.5
`

**Comment by kintsugi** [comment]
@thewei I think this would be solved by changing `peerDependencies` in `package.json` to:

``` json
"peerDependencies": {
        "react-native": ">=0.5 || x-rc"
}
```

I will fork to test.

**Comment by kintsugi** [comment]
Scratch that, tried to run a version range through http://semver.npmjs.com/ but could not get one to work. It seems you can not include all pre-releases from any version. A temporary workaround is to remove the `-rc` tag from the `version` field in `node_modules/react-native/package.json` in your project directory. Then try `npm install react-native-store --save`.

**Comment by thewei** [comment]
v0.2.1 removed peerDependencies
Please try it again.

**Comment by chandu0101** [comment]
wow super fast, its working perfect , thank you :)
