### ISSUE TITLE
Remove with filter doesn't work

### ISSUE THREAD

**Issue by augnustin** [thewei/react-native-store#16]
Hi there,

Great lib!
I can't make the `remove` method work with a filter though.

```
    this.model = await reactNativeStore.model("link");
    // ...
    await this.model.remove({
      where: {
        _id: id,
      }
    });
```

Since it is not in your test suite either, I can't make myself confortable it actually works.

**Comment by kintsugi** [comment]
Hi, thanks for the issue. Is the data you are operating on created before v0.2.0? Before then, the _id field was not written to disk.

However, to be sure I created a new react project to test with [this test code](https://gist.github.com/terminull/ed0869d38e0b03abc272) and got [this output](https://gist.github.com/terminull/358540974ae54ee0f782) which shows that removing by the _id field works.

If your data is created before v0.2.0, it just needs to be re-added to the database to have a _id field. Something like this should work:

``` javascript
this.model = await reactNativeStore.model("link");
var all_data = this.model.remove();
for(var i in all_data) {
    this.model.add(all_data[i]);
}
```

**Comment by thewei** [comment]
Now we had api removeById, you can use this api to remove data by id.
