### ISSUE TITLE
add more meta info to find API response

### ISSUE THREAD

**Issue by chandu0101** [thewei/react-native-store#17]
currently find API returning only array of objects 

```
find({ limit : 10}) // [1..10 objects]
```

it will be cool if it adds more meta info like 

```
{ total : 100 ,rows : [1..10] }
```

**Comment by kintsugi** [comment]
While not exactly the same, you can get the total number of rows like this from an arbitrary model `userModel`

``` javascript
var reactNativeStore = require('react-native-store');
var userModel = reactNativeStore.model('userModel');
var totalRows = userModel.model.totalRows;
```

**Comment by thewei** [comment]
Yes，you can write new api base on react-native-store's api.

**Comment by chandu0101** [comment]
> While not exactly the same, you can get the total number of rows like this from an arbitrary model userModel

but it doesn't solve all cases for example filter and paginate ..

> Yes，you can write new api base on react-native-store's api.

Currently i am doing something similar hack in my scala.js code , it will be cool if its supported out of box in future :)
