### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by chandu0101** [thewei/react-native-store#20]
Hi,
     First of all I am pretty new to this javascript world, when there is an error API blowing up on my face with console errors , instead it should reject a promise with error object isn't it ?

**Comment by thewei** [comment]
Can you be more specific. Do you have screenshots/mocks of what you want the flow to look like?

**Comment by chandu0101** [comment]
when updating record i passed null as id , i got  red screen with ReactNativeStore Error ... , my promise rejection callback never called .

for example : 
https://github.com/thewei/react-native-store/blob/master/libs/store.js#L22 
here it should reject promise with error object ....

**Comment by thewei** [comment]
#24
