### ISSUE TITLE
is it possible to replace entire model data? 

### ISSUE THREAD

**Issue by chandu0101** [thewei/react-native-store#23]
Hi,
      In my app i am backing up client data on server while restoring i want to copy server data to client, is there any API to directly replace all rows of model, instead of remove all and then  adding one by one!.

**Comment by kintsugi** [comment]
Yes. By not passing a where filter (or any filter at all) the whole set of data for the model is used.

``` javascript
var userModel = reactNativeStore.model('user');
userModel.update ({/* new data */});
```

**Comment by chandu0101** [comment]
perfect thanks :)
