### ISSUE TITLE
add null guards for *ById methods

### ISSUE THREAD

**Issue by chandu0101** [thewei/react-native-store#24]
https://github.com/thewei/react-native-store/blob/master/libs/model.js#L172

result can be either null/array , return undefined if its null otherwise pop!

**Comment by chandu0101** [comment]
i think an error object with `id doesn't exist` makes more sense than returning `undefined` , sorry to be the complaining guy instead of sending PR's, i don't have much experience with javascript i am from scala.js :) , if no one up for this i may send PR sometime in future :)

**Comment by thewei** [comment]
I fixed it in react-native-store@0.2.3.

**Comment by chandu0101** [comment]
cool thanks,Its returning null now.how throwing error/rejecting promise because its not a successfull transaction!

**Comment by thewei** [comment]
use promise?

**Comment by chandu0101** [comment]
hmm may be i am completely out of sync(sorry can't understand whats going in js) , *ByID calls are already returns Promise right ? if no id exist then we can reject promise in API level  itself ...

**Comment by thewei** [comment]
Now return a promise object
