### ISSUE TITLE
[question] Source is now babel output?

### ISSUE THREAD

**Issue by klvs** [thewei/react-native-store#25]
I noticed that the source was converted to what appears to be babel output with https://github.com/thewei/react-native-store/commit/22153612742a590d830b372d991c587280e55214

Is there a reason for this? I'd like to contribute more, but I can't make sense of the code anymore. Should we be contributing on a dev branch and have master be babel output (for some reason)?

**Comment by klvs** [comment]
My bad, after looking more closely, we're clearly using src/ now. Should we leave converting libs/ to babel to the merger?

**Comment by thewei** [comment]
Use `babel src --watch --stage 0 --out-dir libs` to build src/, src/ is the source code. 
libs/ is convert by src/

yeah, maybe you are right, we can has a dev branch and master branch.

**Comment by thewei** [comment]
npm version will use babel output now
