### ISSUE TITLE
Like filter

### ISSUE THREAD

**Issue by mcnamee** [thewei/react-native-store#29]
Hi,
You've mentioned that the like filter isn't implemented, is it something on the roadmap?

**Comment by thewei** [comment]
current version use the new filter by @terminull

**Comment by mcnamee** [comment]
Hi @thewei
Sorry if I missed it, are you saying that it is possible to use the like operator (or a similar function)?

**Comment by thewei** [comment]
you can view a simple doc: https://github.com/thewei/react-native-store#filtering
