### ISSUE TITLE
Database limit

### ISSUE THREAD

**Issue by L3V147H4N** [thewei/react-native-store#33]
I'm working on an Enterprise app that must store 40000+ records, when the react-native-store db grows too large it becomes inaccessible because it cannot retrieve a key/value so massive and it throws this error:

```
Error: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
```

In the simulator I'm running this error occurs when the string value reaches about 2300000 characters, I'm not sure if there is workaround possible right now.
I started implementing my own Wrapper which divides each Collection into shards, when I got something working and stable I'll post it.

Thx for the lib anyways, it's very useful in every other way :+1:

**Comment by thewei** [comment]
I think the data is too large, and react-native AsyncStorage isn't the best choose.

**Comment by L3V147H4N** [comment]
Yes, I wrote a very basic wrapper around AsyncStorage that saves the data in "Shards" but it's a weird workaround, I ended up just using SQLite directly, perhaps I'll write a simple ORM instead. thx for your time!

**Comment by forki** [comment]
what do you mean with "shards" how do you split the data with asyncstore?

**Comment by L3V147H4N** [comment]
you split the data into different containers, but it's not very efficient, I just recommend just using SQLite or Realm

**Comment by L3V147H4N** [comment]
https://realm.io/docs/react-native/latest/ or https://github.com/andpor/react-native-sqlite-storage

**Comment by jedt** [comment]
Hi, I encountered this problem as well. I thought using sqlite was overkill (we only had 2-5MB data size) so my solution was to save it as a text file json using https://github.com/johanneslumpe/react-native-fs
