### ISSUE TITLE
Strange error while adding item to model.

### ISSUE THREAD

**Issue by yorzi** [thewei/react-native-store#40]
Hi, I tried to use `react-native-store` according the simple sample in README file. It seems the `add` function is not working as you described in that sample.

I firstly created below `user` model.

```
var reactNativeStore = require('react-native-store');

var DB = {
  'user': new reactNativeStore.model('user'),
}

module.exports = DB;
```

Then I tried to add some item:

```
        DB.user.add({
          'accessToken': jsonRes.token,
        }).then(resp => console.log('Added Item: ',resp));
```

I kept getting below issue:

<img width="779" alt="screen shot 2016-01-21 at 6 48 42 pm" src="https://cloud.githubusercontent.com/assets/38976/12478504/38ed1e1c-c070-11e5-83bf-2bdef601f59e.png">

Could you give me a hand on this issue? Do you know if the error is related to `react-native-store`?

Thanks a lot!

**Comment by thewei** [comment]
the document has a error. please fix it like this:

```
var DB = {
  'user': reactNativeStore.model('user'),
}
```

**Comment by yorzi** [comment]
@thewei thanks, it works now.
