### ISSUE TITLE
about data persistent

### ISSUE THREAD

**Issue by ha-family** [thewei/react-native-store#41]
hi ~
sometimes data missing when i refresh js on simulator
can you explain why? how to store data permanently??

**Comment by thewei** [comment]
I never missing data before when use simulator
react-native-store is base on react-native AsyncStorage
you can ask other react-native user, maybe they had the answer.

**Comment by dattran92** [comment]
I have the same problem. Don't know what's wrong which AsyncStorage in react-native using emulator.

**Comment by ha-family** [comment]
don't worry dattran, it won't lose data when you deploy on your mobile phone
i've tried ~ but don't use 

> destroy

 because the function is not only delete the storage you declare at first
it will delete all data ~
